services:
  - type: web
    name: sistema-servicios-automotrices
    env: python
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python init_db.py
      if [ $? -eq 0 ]; then
        gunicorn app:app --bind 0.0.0.0:$PORT
      else
        echo "Database initialization failed"
        exit 1
      fi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-servicios-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production